### ISSUE TITLE
Session auto-login stuff

### ISSUE THREAD

**Issue by Geo1088** [Geo1088/wix-maybe#10]
- [ ] Make the "am I logged in already?" check also use HTTP for consistency
- [ ] Make said HTTP request return user information we can use to update the UI

Related bug: Opening the page with an active session will log you in but not show your username anywhere on the page, because the client doesn't know it.

**Comment by eritbh** [comment]
i dont even know if this is relevant or not anymore so i'm going to close it because fk u
