### ISSUE TITLE
Tabbed global chat

### ISSUE THREAD

**Issue by Geo1088** [Geo1088/wix-maybe#2]
- [x] Tabs in interface (done in 1808f2b along with some other stuff)
    - [ ] Figure out a final style for these
- [ ] Support being in multiple chat rooms at once

this is gonna be pretty cool tbh

**Comment by Geo1088** [comment]
I wanna say this is done other than the tabs being orange

**Comment by Geo1088** [comment]
styling changes in c2cfcaef49d0aff95338730ff62e310e00efed7b

**Comment by eritbh** [comment]
i can close this now
